import type { Metadata } from "next";
import "./globals.css";
import AuthBlock from "./lib/components/AuthBlock";
import Navbar from "./ui/Navbar";
import SplashScreen from "./ui/loaders/SplashScreen";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/satoshi" rel="stylesheet" />
        <link rel="icon" href="/tab-icon.svg" type="image/svg" />
      </head>
      <body className={`antialiased min-h-screen`}>
        <Navbar />
        <AuthBlock>
          <div>{children}</div>
        </AuthBlock>
        <SplashScreen />
      </body>
    </html>
  );
}
