"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import {
  ArrowDown2,
  ArrowLeft2,
  CloseCircle,
  Copy,
  DocumentDownload,
  Eye,
  Heart,
  Magicpen,
  Refresh2,
} from "iconsax-react";
import Preview from "@/app/ui/campaign-snapshots/Preview";
import { useCreateCampaignStore } from "@/app/lib/stores/createCampaignStore";
import { Platform } from "@/type";
import Product from "@/app/ui/campaign-snapshots/Product";
import ProductsForGeneration from "@/app/ui/campaign-snapshots/ProductsForGeneration";
import Input from "@/app/ui/form/Input";
import CampaignTypeInput from "@/app/ui/campaign-snapshots/CampaigtTypeInput";
import BrandColors from "@/app/ui/campaign-snapshots/BrandColors";
import { getCampaignTypes } from "@/app/lib/campaignTypes";
import { ShopifyProduct } from "@/type";
import CompetitorAds from "@/app/ui/dashboard/CompetitorAds";
import AdLibrary from "@/app/ui/dashboard/AdLibrary";
import useCreativesStore from "@/app/lib/stores/creativesStore";
import { useGenerateCreatives } from "@/app/lib/hooks/creatives";

type SelectedProduct = {
  id: string;
  title: string;
  price: string;
  imageUrl: string;
};

type StoredPayload = {
  source: string;
  adId: string;
  selectedProducts: SelectedProduct[];
  createdAt: string;
};

type ViewDetailsAd = {
  id: number;
  brand: string;
  domain: string;
  productName: string;
  headline: string;
  platform: "meta" | "tiktok";
  previewType: "image" | "video";
  previewUrl: string;
  adScore: number;
  niche: string;
  subNiche: string;
  cta: string;
  daysAgo?: number;
  isNew?: boolean;
  saved?: boolean;
};

const productTypes = getCampaignTypes();

const ProductContainer = ({
  products,
  highlightedProduct,
  handleSetHighlightedProduct,
}: {
  products: ShopifyProduct[];
  highlightedProduct: ShopifyProduct | null;
  handleSetHighlightedProduct: (product: ShopifyProduct) => void;
}) => {
  return (
    <div className="w-[224px] sticky custom-shadow-sm top-20 flex-shrink-0 flex flex-col gap-6 px-1 py-6 bg-[#FBFAFC] rounded-3xl max-h-[calc(100vh-200px)]">
      <div className="flex justify-between gap-2 px-3">
        <span className="text-sm font-medium">Products</span>
        <span>
          <ArrowDown2 size={12} color="#000" />
        </span>
      </div>
      <div className="flex flex-col w-full gap-5 flex-1 break-words pink-scroll overflow-x-hidden overflow-y-auto px-3">
        {products.map((product) => (
          <Product
            product={product}
            key={product.node.id}
            highlightedProduct={highlightedProduct}
            handleSetHighlightedProduct={handleSetHighlightedProduct}
          />
        ))}
      </div>
    </div>
  );
};

export default function V2CreateCampaignPreviewPage() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const source = searchParams.get("source") || "unknown";
  const adId = searchParams.get("adId") || "";

  const [payload, setPayload] = useState<StoredPayload | null>(null);
  const [showInsights, setShowInsights] = useState(false);
  const [showReplaceAdModal, setShowReplaceAdModal] = useState(false);
  const [replaceSource, setReplaceSource] = useState<"competitor" | "library">(
    (searchParams.get("source") as "competitor" | "library") || "competitor"
  );

  const {
    actions,
    instagramSettings,
    facebookSettings,
    campaignSnapshots,
    productSelection,
  } = useCreateCampaignStore((state) => state);

  const [error, setError] = useState(false);
  const [highlightedProduct, setHighlightedProduct] = useState<ShopifyProduct | null>(null);

  const { generateCreatives, loading: creativesLoading } = useGenerateCreatives();
  const [autoGenerated, setAutoGenerated] = useState<Record<string, boolean>>({});

  useEffect(() => {
    window.scrollTo({ top: 0, left: 0, behavior: "instant" as ScrollBehavior });
  }, []);

  const sourceLabel = useMemo(() => {
    const v = (payload?.source || source || "unknown").toLowerCase();
    if (v === "competitor") return "Competitor";
    if (v === "library") return "Use Our Ready Made Creative Templates";
    if (v === "campaign") return "Campaign";
    if (v === "shopify") return "Shopify Products";
    return payload?.source || source || "Unknown";
  }, [payload?.source, source]);

  const adLabel = useMemo(() => {
    const id = payload?.adId || adId;
    if (!id) return "—";
    return `Ad ${id}`;
  }, [payload?.adId, adId]);


  const viewDetailsAd = useMemo<ViewDetailsAd>(() => {
    const idStr = payload?.adId || adId;
    const parsedId = Number(idStr);
    const numericId = Number.isFinite(parsedId) ? parsedId : 0;
    const sourceValue = (payload?.source || source || "").toLowerCase();
    const isCompetitor = sourceValue === "competitor";
    const isCampaign = sourceValue === "campaign";
    const isShopify = sourceValue === "shopify";

    return {
      id: numericId,
      brand: isCompetitor
        ? "Competitor"
        : isCampaign
          ? "Campaign"
          : isShopify
            ? "Shopify"
            : "Use Our Ready Made Creative Templates",
      domain: "example.com",
      productName: "Cloned Ad",
      headline: "Prototype: this is the original ad you selected to clone.",
      platform: "meta",
      previewType: "image",
      previewUrl: "/ad-assets/6da1073c-b66a-4448-9269-80afa64e9ac9_1766197795895.png",
      adScore: 92,
      niche: "—",
      subNiche: "—",
      cta: "Shop now",
      daysAgo: 7,
      isNew: false,
      saved: false,
    };
  }, [payload?.adId, payload?.source, adId, source]);

  const canShowOriginalAdActions = useMemo(() => {
    return !!(payload?.adId || adId);
  }, [payload?.adId, adId]);

  const getEstimatedReach = (ad: ViewDetailsAd) => {
    if (ad.isNew) return "—";
    if (!ad.daysAgo) return "—";
    if (ad.daysAgo >= 30) return "100K+";
    if (ad.daysAgo >= 14) return "50K+";
    if (ad.daysAgo >= 7) return "20K+";
    return "5K+";
  };

  const getAdStartDate = (ad: ViewDetailsAd) => {
    if (!ad.daysAgo) return "—";
    const d = new Date();
    d.setDate(d.getDate() - ad.daysAgo);
    return d.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" });
  };

  useEffect(() => {
    try {
      const raw = sessionStorage.getItem("v2_create_campaign");
      if (!raw) return;
      const parsed = JSON.parse(raw) as StoredPayload;
      setPayload(parsed);
    } catch {
      // ignore
    }
  }, []);

  const selectedProducts = useMemo(() => payload?.selectedProducts ?? [], [payload]);

  const storeProducts = useMemo<ShopifyProduct[]>(() => {
    return selectedProducts.map((p) => {
      const amount = String(p.price).replace(/[^0-9.]/g, "") || "0";
      return {
        node: {
          id: p.id,
          title: p.title,
          description: "",
          handle: p.id,
          category: { fullName: "", id: "", name: "" },
          onlineStorePreviewUrl: "",
          tags: [],
          productType: "",
          hasOnlyDefaultVariant: true,
          media: {
            edges: [
              {
                node: {
                  id: `${p.id}_img`,
                  mediaContentType: "IMAGE",
                  preview: {
                    image: {
                      url: p.imageUrl,
                      alt: p.title,
                    },
                  },
                },
              },
            ],
          },
          priceRangeV2: {
            maxVariantPrice: { amount, currencyCode: "USD" },
            minVariantPrice: { amount, currencyCode: "USD" },
          },
          variants: [],
        },
      } as ShopifyProduct;
    });
  }, [selectedProducts]);

  useEffect(() => {
    if (!storeProducts.length) return;

    actions.storeProductSelection({
      products: storeProducts,
      complete: true,
    });

    actions.setAdsPlatform("Google", false);
    actions.setAdsPlatform("Instagram", true);
    actions.setAdsPlatform("Facebook", true);
    actions.completeAdsPlatform();

    setHighlightedProduct(storeProducts[0]);
  }, [actions, storeProducts]);

  useEffect(() => {
    if (!highlightedProduct?.node.id) return;
    const productId = highlightedProduct.node.id;
    if (autoGenerated[productId]) return;

    setAutoGenerated((prev) => ({ ...prev, [productId]: true }));
    generateCreatives(productId, ["INSTAGRAM", "FACEBOOK"]);
  }, [autoGenerated, generateCreatives, highlightedProduct?.node.id]);

  useEffect(() => {
    if (!highlightedProduct && productSelection.products.length > 0) {
      setHighlightedProduct(productSelection.products[0]);
    }
  }, [highlightedProduct, productSelection.products]);

  const highlightedProductId =
    highlightedProduct?.node.id || productSelection.products?.[0]?.node.id || "1";

  const { Instagram, Facebook } = useCreativesStore((state) => state);

  const adPlatforms = useMemo(
    () => {
      const instagramCreatives = Instagram?.[highlightedProductId] ?? [{ creatives: [] }];
      const facebookCreatives = Facebook?.[highlightedProductId] ?? [{ creatives: [] }];

      return [
        {
          title: "Instagram" as const,
          platform: "INSTAGRAM" as Platform,
          image: "/instagram_logo.svg",
          settings: instagramSettings,
          creatives: instagramCreatives,
        },
        {
          title: "Facebook" as const,
          platform: "FACEBOOK" as Platform,
          image: "/facebook_logo.svg",
          settings: facebookSettings,
          creatives: facebookCreatives,
        },
      ];
    },
    [Facebook, Instagram, facebookSettings, highlightedProductId, instagramSettings]
  );

  const handleRegenerate = () => {
    if (highlightedProduct?.node.id) {
      generateCreatives(highlightedProduct.node.id, ["INSTAGRAM", "FACEBOOK"]);
    }
  };

  const handleCampaignDetails = (
    key: keyof typeof campaignSnapshots,
    value: string
  ) => {
    actions.storeCampaignSnapshots({ ...campaignSnapshots, [key]: value });
  };

  const handleSetHighlightedProduct = (product: ShopifyProduct) => {
    setHighlightedProduct(product);
  };

  const handleDownload = () => {
    const productId = highlightedProductId;
    const igLast = Instagram?.[productId]?.[Instagram[productId].length - 1];
    const fbLast = Facebook?.[productId]?.[Facebook[productId].length - 1];

    const igUrl = igLast?.creatives?.[0]?.url;
    const fbUrl = fbLast?.creatives?.[0]?.url;

    const fallbackUrl =
      highlightedProduct?.node?.media?.edges?.[0]?.node?.preview?.image?.url ||
      productSelection.products?.[0]?.node?.media?.edges?.[0]?.node?.preview?.image?.url ||
      selectedProducts?.[0]?.imageUrl ||
      "";

    const url = igUrl || fbUrl || fallbackUrl;
    if (!url) return;

    const name = (highlightedProduct?.node?.title || "creative")
      .replace(/\s+/g, "-")
      .toLowerCase();

    const link = document.createElement("a");
    link.href = url;
    link.download = `${name}-asset`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleReplaceAd = (nextSource: "competitor" | "library", nextAdId: number) => {
    setReplaceSource(nextSource);

    const nextPayload: StoredPayload = {
      source: nextSource,
      adId: String(nextAdId),
      selectedProducts: payload?.selectedProducts ?? [],
      createdAt: payload?.createdAt ?? new Date().toISOString(),
    };

    try {
      sessionStorage.setItem("v2_create_campaign", JSON.stringify(nextPayload));
    } catch {
      // ignore
    }

    setPayload(nextPayload);
    setShowReplaceAdModal(false);

    const qs = new URLSearchParams();
    qs.set("source", nextSource);
    qs.set("adId", String(nextAdId));
    router.replace(`/dashboard-v2/create-campaign/preview?${qs.toString()}`);
  };

  return (
    <div className="min-h-[calc(100vh-56px)] px-6 lg:px-10 pb-12">
      <div className="max-w-6xl mx-auto">
        <div className="flex px-5 lg:px-0 items-center h-[40px] mt-6 justify-between">
          <button
            onClick={() => router.push("/dashboard-v2/create-campaign/product-selection")}
            className="flex items-center cursor-pointer gap-2"
          >
            <ArrowLeft2 size={20} color="#333" className="block" />
            <span className="text-sm md:text-lg tracking-250 font-medium">Select Products</span>
          </button>
        </div>

        <div className="flex items-start flex-shrink-0 gap-6 mt-6 pb-12">
          {productSelection.products.length > 0 && (
            <div className="hidden w-[224px] lg:block sticky top-20 flex-shrink-0">
              <ProductContainer
                highlightedProduct={highlightedProduct}
                products={productSelection.products}
                handleSetHighlightedProduct={handleSetHighlightedProduct}
              />
            </div>
          )}

          <div className="w-full lg:w-[calc(100%-248px)] max-w-full">
            <div className="flex px-5 lg:pl-0 lg:pr-5 flex-col lg:flex-row gap-3 justify-between">
              <div className="flex flex-col lg:flex-row gap-3 justify-between">
                <div>
                  <h1 className="text-xl tracking-40 md:text-2xl font-medium md:font-bold text-heading md:tracking-800">
                    <span className="num">3. </span>
                    <span>Campaign Snapshots</span>
                  </h1>
                  <p className="mt-[0.38rem] text-neutral-light tracking-40 text-xs md:text-sm my-2 md:my-0">
                    Here's a view of how your brand will be showcased across multiple ad platforms.
                  </p>
                </div>
              </div>

              <div className="hidden px-5 lg:pl-0 lg:pr-5 lg:block">
                <div className="flex gap-2 md:gap-3">
                  <button
                    onClick={handleDownload}
                    className="flex items-center gap-2 h-[40px] w-[134px] rounded-[39px] justify-center bg-[#F0E6FB] border-[#D0B0F3] border"
                  >
                    <DocumentDownload size={18} color="#000" />
                    <span className="text-sm font-medium">Download</span>
                  </button>
                  <button
                    onClick={() => {
                      handleRegenerate();
                    }}
                    className="flex items-center gap-2 h-[40px] w-[134px] rounded-[39px] justify-center bg-[#F0E6FB] border-[#D0B0F3] border"
                  >
                    <Magicpen size={18} color="#000" />
                    <span className="text-sm font-medium">Regenerate</span>
                  </button>
                </div>
              </div>
            </div>

            <div className="px-5 lg:pl-0 lg:pr-5">
              <ProductsForGeneration
                highlightedProductId={highlightedProductId}
                setHighlightedProduct={setHighlightedProduct}
              />
            </div>

            <div className="flex px-5 lg:pl-0 lg:pr-5 flex-row justify-end mt-6 lg:hidden">
              <div className="flex gap-2 md:gap-3">
                <button
                  onClick={handleDownload}
                  className="flex items-center gap-2 h-[40px] w-[134px] rounded-[39px] justify-center bg-[#F0E6FB] border-[#D0B0F3] border"
                >
                  <DocumentDownload size={18} color="#000" />
                  <span className="text-sm font-medium">Download</span>
                </button>
                <button
                  onClick={() => {
                    handleRegenerate();
                  }}
                  className="flex items-center gap-2 h-[40px] w-[134px] rounded-[39px] justify-center bg-[#F0E6FB] border-[#D0B0F3] border"
                >
                  <Magicpen size={18} color="#000" />
                  <span className="text-sm font-medium">Regenerate</span>
                </button>
              </div>
            </div>

            <div className="mt-6 px-5 lg:pl-0 lg:pr-5">
              <Input
                type="text"
                label="Campaign Name"
                name="campaignName"
                placeholder="My Campaign"
                large
                onBlur={() => setError(false)}
                background="rgba(232,232,232,0.35)"
                borderless
                error={error ? "Campaign name is required" : ""}
                value={campaignSnapshots.campaignName}
                onChange={(e) => handleCampaignDetails("campaignName", e.target.value)}
              />
            </div>

            <div className="mt-5 px-5 lg:pl-0 lg:pr-5 flex flex-col md:flex-row gap-4 md:gap-14">
              <div className="flex-1">
                <div className="w-full">
                  <CampaignTypeInput
                    label="Campaign Type"
                    placeholder="Product Launch"
                    options={productTypes}
                    background="rgba(232,232,232,0.35)"
                    borderless
                    selected={campaignSnapshots.campaignType}
                    setSelected={(value: string) => handleCampaignDetails("campaignType", value)}
                    large
                    setError={() => setError(false)}
                  />
                </div>
              </div>

              <BrandColors
                brandColor={campaignSnapshots.brandColor}
                accentColor={campaignSnapshots.accentColor}
                setBrandColor={(key: "brandColor" | "accentColor", value: string) =>
                  handleCampaignDetails(key, value)
                }
              />
            </div>

            <div className="px-5 lg:pl-0 lg:pr-5">
              <div className="mt-4 w-full bg-[rgba(232,232,232,0.35)] rounded-2xl px-5 py-4">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4 items-start">
                  <div>
                    <div className="text-xs md:text-sm text-neutral-light">Source</div>
                    <div className="mt-1 text-sm md:text-base font-medium text-heading">
                      {sourceLabel}
                    </div>
                  </div>

                  <div>
                    <div className="text-xs md:text-sm text-neutral-light">Ad name</div>
                    <div className="mt-1 text-sm md:text-base font-medium text-heading">
                      {adLabel}
                    </div>
                  </div>

                  <div className="flex md:justify-end">
                    <div className="flex flex-wrap items-center justify-end gap-2">
                      <button
                        type="button"
                        onClick={() => {
                          const current = (payload?.source || source || "competitor") as
                            | "competitor"
                            | "library";
                          setReplaceSource(current);
                          setShowReplaceAdModal(true);
                        }}
                        className="h-[40px] px-4 rounded-xl bg-white/60 border border-[#E8E5EC] text-xs md:text-sm font-medium text-heading hover:bg-white transition-colors flex items-center gap-2 whitespace-nowrap"
                      >
                        <Refresh2 size={18} color="#333" />
                        Change Source
                      </button>
                      <button
                        type="button"
                        disabled={!canShowOriginalAdActions}
                        onClick={() => {
                          if (!canShowOriginalAdActions) return;
                          setShowInsights(true);
                        }}
                        className={`h-[40px] px-4 rounded-xl bg-white/60 border border-[#E8E5EC] text-xs md:text-sm font-medium text-heading transition-colors flex items-center gap-2 whitespace-nowrap ${
                          canShowOriginalAdActions
                            ? "hover:bg-white"
                            : "opacity-50 cursor-not-allowed"
                        }`}
                      >
                        <Eye size={18} color="#333" />
                        View original ad
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-10">
              <Preview
                adPlatforms={adPlatforms}
                highlightedProductId={highlightedProductId}
                generateCreatives={generateCreatives}
                loading={creativesLoading}
                hidePlatformRegenerate
              />
            </div>

            <div className="mt-8 px-5 lg:pl-0 lg:pr-5 flex justify-center">
              <button
                onClick={() => {
                  if (campaignSnapshots.campaignName.trim() === "") {
                    setError(true);
                    window.scrollTo({ top: 0, behavior: "smooth" });
                    return;
                  }
                  setError(false);
                  router.push("/dashboard-v2/campaigns");
                }}
                className="px-8 py-3 rounded-xl text-sm font-medium bg-gradient-to-r from-[#A755FF] to-[#6800D7] text-white hover:brightness-95 transition-[filter]"
              >
                Save campaign
              </button>
            </div>

            {showInsights ? (
              <div
                className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
                onClick={() => setShowInsights(false)}
              >
                <div
                  className="bg-white rounded-2xl max-w-6xl w-full max-h-[85vh] overflow-hidden"
                  onClick={(e) => e.stopPropagation()}
                >
                  <div className="p-4 border-b border-[#F3EFF6] flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-full bg-gradient-to-r from-[#A755FF] to-[#6800D7] flex items-center justify-center">
                        <span className="text-sm text-white font-medium">
                          {viewDetailsAd.brand.charAt(0)}
                        </span>
                      </div>
                      <div>
                        <h3 className="text-purple-dark font-semibold">{viewDetailsAd.brand}</h3>
                        <div className="flex items-center gap-2 text-gray-dark text-xs">
                          <span className="truncate">{viewDetailsAd.subNiche}</span>
                          <span className="text-gray-light">•</span>
                          <span className="flex items-center gap-1">
                            <img src="/instagram_logo.svg" alt="Instagram" className="w-3.5 h-3.5" />
                            <img src="/facebook.svg" alt="Facebook" className="w-3.5 h-3.5" />
                          </span>
                        </div>
                      </div>
                    </div>
                    <div className="relative flex items-center gap-2 z-10">
                      <button
                        onClick={(e) => e.stopPropagation()}
                        className="p-2 rounded-lg border border-[#F3EFF6] bg-white transition-colors hover:bg-[#F3EFF6] text-gray-dark hover:text-purple-dark"
                        aria-label="Save ad"
                      >
                        <Heart size={20} variant="Linear" color="#737373" />
                      </button>
                      <button
                        onClick={(e) => e.stopPropagation()}
                        className="p-2 rounded-lg border border-[#F3EFF6] bg-white text-gray-dark hover:text-purple-dark hover:bg-[#F3EFF6] transition-colors"
                        aria-label="Clone ad"
                      >
                        <Copy size={20} color="#737373" />
                      </button>
                      <button
                        onClick={() => setShowInsights(false)}
                        className="p-2 rounded-lg border border-[#F3EFF6] bg-white text-gray-dark hover:text-purple-dark hover:bg-[#F3EFF6] transition-colors"
                        aria-label="Close"
                      >
                        <CloseCircle size={24} className="text-gray-dark" color="#737373" />
                      </button>
                    </div>
                  </div>

                  <div className="grid grid-cols-1 lg:grid-cols-[420px_1fr] h-[calc(85vh-73px)]">
                    <div className="border-b lg:border-b-0 lg:border-r border-[#F3EFF6] p-4">
                      <div className="bg-[#F3EFF6] overflow-hidden relative h-[420px] lg:h-full">
                        {viewDetailsAd.previewType === "video" ? (
                          <video
                            src={viewDetailsAd.previewUrl}
                            className="w-full h-full object-cover"
                            controls
                            playsInline
                          />
                        ) : (
                          <img
                            src={viewDetailsAd.previewUrl}
                            alt={viewDetailsAd.productName}
                            className="w-full h-full object-cover"
                          />
                        )}
                      </div>
                      <div className="mt-3">
                        <p className="text-gray-dark text-xs truncate">{viewDetailsAd.domain}</p>
                        <p className="text-purple-dark font-semibold">{viewDetailsAd.productName}</p>
                      </div>
                    </div>

                    <div className="overflow-auto p-4 space-y-4">
                      <div className="bg-[#F3EFF6] rounded-2xl p-4">
                        <div className="flex items-center justify-between gap-4">
                          <div>
                            <p className="text-gray-dark text-xs">Ad Score</p>
                            <p className="text-purple-dark text-2xl font-extrabold leading-none">
                              {viewDetailsAd.adScore}
                            </p>
                          </div>
                          <button
                            className="px-3 py-2 bg-white text-purple-dark text-sm rounded-xl shadow-sm hover:bg-[#FAF7FC] transition-colors font-medium"
                            onClick={(e) => e.stopPropagation()}
                          >
                            View scoring factors
                          </button>
                        </div>
                        <div className="mt-3 text-[12px] text-gray-dark space-y-1">
                          <p>Running 30+ days</p>
                          <p>
                            {viewDetailsAd.previewType === "video"
                              ? "Video used across multiple campaigns"
                              : "Image used across multiple campaigns"}
                          </p>
                          <p>Multiple languages or regions</p>
                          <p>Includes proof and CTA</p>
                          <p>Has strong storytelling</p>
                        </div>
                      </div>

                      <div className="bg-[#F3EFF6] rounded-2xl p-4">
                        <h4 className="text-purple-dark font-semibold mb-2">Ad Copy</h4>
                        <p className="text-gray-dark text-sm">{viewDetailsAd.headline}</p>
                      </div>

                      <div className="bg-[#F3EFF6] rounded-2xl p-4">
                        <h4 className="text-purple-dark font-semibold mb-3">Ad Details</h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Platform</p>
                            <p className="font-medium text-sm text-purple-dark capitalize">
                              {viewDetailsAd.platform}
                            </p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Ad Type</p>
                            <p className="font-medium text-sm text-purple-dark capitalize">
                              {viewDetailsAd.previewType}
                            </p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Niche</p>
                            <p className="font-medium text-sm text-purple-dark">{viewDetailsAd.niche}</p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Sub-Niche</p>
                            <p className="font-medium text-sm text-purple-dark">{viewDetailsAd.subNiche}</p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Days Running</p>
                            <p className="font-medium text-sm text-purple-dark">
                              {viewDetailsAd.daysAgo ? `${viewDetailsAd.daysAgo} days` : "New"}
                            </p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Start Date</p>
                            <p className="font-medium text-sm text-purple-dark">{getAdStartDate(viewDetailsAd)}</p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">Reach</p>
                            <p className="font-medium text-sm text-purple-dark">{getEstimatedReach(viewDetailsAd)}</p>
                          </div>
                          <div className="bg-white rounded-xl p-3">
                            <p className="text-gray-dark text-xs mb-1">CTA</p>
                            <p className="font-medium text-sm text-purple-dark">{viewDetailsAd.cta}</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            ) : null}

            {showReplaceAdModal ? (
              <div
                className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4"
                onClick={() => setShowReplaceAdModal(false)}
              >
                <div
                  className="bg-white rounded-2xl max-w-6xl w-full max-h-[85vh] overflow-hidden"
                  onClick={(e) => e.stopPropagation()}
                >
                  <div className="p-4 border-b border-[#F3EFF6] flex items-center justify-between">
                    <div>
                      <div className="text-purple-dark font-semibold">Replace selected ad</div>
                      <div className="text-xs text-gray-500 mt-1">
                        Switch between competitor ads and templates, then pick a new one.
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => setShowReplaceAdModal(false)}
                      className="p-2 rounded-lg border border-[#F3EFF6] bg-white text-gray-dark hover:text-purple-dark hover:bg-[#F3EFF6] transition-colors"
                      aria-label="Close"
                    >
                      <CloseCircle size={24} className="text-gray-dark" color="#737373" />
                    </button>
                  </div>

                  <div className="p-4">
                    <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
                      <div className="flex items-center gap-2">
                        <button
                          type="button"
                          onClick={() => setReplaceSource("competitor")}
                          className={`h-[36px] px-4 rounded-xl text-sm font-medium border transition-colors whitespace-nowrap ${
                            replaceSource === "competitor"
                              ? "bg-[#F3EFF6] border-[#D0B0F3] text-purple-dark"
                              : "bg-white border-[#E8E5EC] text-gray-dark hover:bg-[#F3EFF6]"
                          }`}
                        >
                          Clone Competitor Ads
                        </button>
                        <button
                          type="button"
                          onClick={() => setReplaceSource("library")}
                          className={`h-[36px] px-4 rounded-xl text-sm font-medium border transition-colors whitespace-nowrap ${
                            replaceSource === "library"
                              ? "bg-[#F3EFF6] border-[#D0B0F3] text-purple-dark"
                              : "bg-white border-[#E8E5EC] text-gray-dark hover:bg-[#F3EFF6]"
                          }`}
                        >
                          Use Our Ready Made Creative Templates
                        </button>
                      </div>

                      <div className="text-xs text-gray-500">
                        Current: <span className="font-medium text-gray-700">{sourceLabel}</span>
                        <span className="text-gray-400"> • </span>
                        <span className="font-medium text-gray-700">{adLabel}</span>
                      </div>
                    </div>

                    <div className="mt-4 overflow-auto max-h-[calc(85vh-170px)] pr-1">
                      {replaceSource === "competitor" ? (
                        <CompetitorAds
                          onSelectAd={(nextAdId) => handleReplaceAd("competitor", nextAdId)}
                        />
                      ) : (
                        <AdLibrary
                          onSelectAd={(nextAdId) => handleReplaceAd("library", nextAdId)}
                        />
                      )}
                    </div>
                  </div>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </div>
    </div>
  );
}
